[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
cozy-chess = "0.3"
ndarray = "0.17.2"
ort = { version = "2.0.0-rc.11", features = ["cuda"] }
openssl = { version = "0.10", features = ["vendored"] }
